# Generated by Django 6.0.4 on 2026-05-16 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceabilityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BATCH_CREATED', "Lot créé par l'agriculteur"), ('RECEIVED_BY_COOP', 'Reçu par la coopérative'), ('IN_TRANSIT', 'En transit (Transporteur)'), ('DELIVERED_EXPORTER', "Livré à l'exportateur"), ('CERTIFIED', 'Certifié (Fairtrade / Bio EU / RA)'), ('EXPORTED', "Exporté vers l'UE"), ('QR_SCANNED', 'QR Code scanné par un acheteur')], max_length=30)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BatchCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_type', models.CharField(choices=[('fairtrade', 'Fairtrade International'), ('bio_eu', 'Agriculture Biologique UE'), ('rainforest', 'Rainforest Alliance'), ('eudr_compliant', 'Conforme EUDR 2025'), ('custom', 'Autre certification')], default='custom', max_length=30)),
                ('certification_name', models.CharField(help_text='Nom exact du label', max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='stock.batch')),
            ],
        ),
    ]
