# Generated by Django 6.0.4 on 2026-05-16 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_initial'),
        ('tracability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcertification',
            name='certifier',
            field=models.ForeignKey(limit_choices_to={'is_certifier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='issued_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traceabilityevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text="L'entité qui a effectué cet événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traceability_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traceabilityevent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_events', to='stock.batch'),
        ),
        migrations.AddIndex(
            model_name='traceabilityevent',
            index=models.Index(fields=['batch'], name='idx_trace_batch'),
        ),
        migrations.AddIndex(
            model_name='traceabilityevent',
            index=models.Index(fields=['event_type'], name='idx_trace_event'),
        ),
    ]
