# Generated by Django 6.0.4 on 2026-05-15 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stockproducer_farm_and_more'),
        ('tracability', '0003_batchcertification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcertification',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='stock.batch'),
        ),
        migrations.RemoveField(
            model_name='transactionevent',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='transactionevent',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transactionevent',
            name='sender',
        ),
        migrations.AddField(
            model_name='batchcertification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='batchcertification',
            name='certification_type',
            field=models.CharField(choices=[('fairtrade', 'Fairtrade International'), ('bio_eu', 'Agriculture Biologique UE'), ('rainforest', 'Rainforest Alliance'), ('eudr_compliant', 'Conforme EUDR 2025'), ('custom', 'Autre certification')], default='custom', max_length=30),
        ),
        migrations.AddField(
            model_name='batchcertification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchcertification',
            name='certification_name',
            field=models.CharField(help_text='Nom exact du label', max_length=100),
        ),
        migrations.AlterField(
            model_name='batchcertification',
            name='certifier',
            field=models.ForeignKey(limit_choices_to={'is_certifier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='issued_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchcertification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TraceabilityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BATCH_CREATED', "Lot créé par l'agriculteur"), ('RECEIVED_BY_COOP', 'Reçu par la coopérative'), ('IN_TRANSIT', 'En transit (Transporteur)'), ('DELIVERED_EXPORTER', "Livré à l'exportateur"), ('CERTIFIED', 'Certifié (Fairtrade / Bio EU / RA)'), ('EXPORTED', "Exporté vers l'UE"), ('QR_SCANNED', 'QR Code scanné par un acheteur')], max_length=30)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text="L'entité qui a effectué cet événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traceability_actions', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_events', to='stock.batch')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ProductBatch',
        ),
        migrations.DeleteModel(
            name='TransactionEvent',
        ),
        migrations.AddIndex(
            model_name='traceabilityevent',
            index=models.Index(fields=['batch'], name='idx_trace_batch'),
        ),
        migrations.AddIndex(
            model_name='traceabilityevent',
            index=models.Index(fields=['event_type'], name='idx_trace_event'),
        ),
    ]
