# Generated by Django 6.0.4 on 2026-05-14 11:06

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profilepic_id_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracaouser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_certifier',
        ),
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_cooperative_destination',
        ),
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_cooperative_source',
        ),
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_eu_importer',
        ),
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_exporter',
        ),
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_government',
        ),
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_producer',
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='hired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='is_private_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='is_transformer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='legal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='org_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='person_to_call',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='ptc_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='record_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='situation_geo',
            field=models.CharField(blank=True, default='Lome', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='store_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='store_certification',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='store_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='tax_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
