# Generated by Django 6.0.4 on 2026-05-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tracaouser_is_verified_magiclink_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracaouser',
            name='is_certifier',
            field=models.BooleanField(default=False),
        ),
    ]
