services:
  - type: web
    name: tracao-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python tracao/manage.py collectstatic --no-input
      python tracao/manage.py migrate
      python tracao/manage.py set_superuser
    startCommand: gunicorn --pythonpath tracao tracao.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - fromGroup: tracao-env
