# Generated by Django 6.0.4 on 2026-05-16 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='validated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_store': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchtransfer',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='stock.batch'),
        ),
        migrations.AddField(
            model_name='batchtransfer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchtransfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='stock.batch'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='validated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_store': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.parcel'),
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['batch'], name='idx_transfers_batch'),
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['sender'], name='idx_transfers_sender'),
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['receiver'], name='idx_transfers_receiver'),
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['status'], name='idx_transfers_status'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['batch'], name='idx_harvests_batch'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_date'], name='idx_harvests_date'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['farmer'], name='idx_parcels_farmer'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='idx_parcels_status'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['farmer'], name='idx_batches_farmer'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['parcel'], name='idx_batches_parcel'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='idx_batches_status'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['unique_code'], name='idx_batches_code'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('parcel', 'season', 'crop_type')},
        ),
    ]
