# Generated by Django 6.0.4 on 2026-05-15 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockdestination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproducer',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='stockdestination',
            name='exporter',
        ),
        migrations.RemoveField(
            model_name='stockdestination',
            name='stock_transporter',
        ),
        migrations.RemoveField(
            model_name='stockdestination',
            name='transporter',
        ),
        migrations.RemoveField(
            model_name='stockorigin',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='stockorigin',
            name='producer_stock',
        ),
        migrations.RemoveField(
            model_name='stocktransporter',
            name='stock_origin',
        ),
        migrations.RemoveField(
            model_name='stockproducer',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='stockproducer',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='stocktransporter',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='stocktransporter',
            name='transporter',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(help_text='Ex: 2025-2026', max_length=50)),
                ('crop_type', models.CharField(choices=[('cacao', 'Cacao'), ('cafe', 'Café')], max_length=20)),
                ('estimated_quantity', models.FloatField(help_text='Quantité estimée en kg')),
                ('actual_quantity', models.FloatField(blank=True, help_text='Quantité réelle pesée en kg', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'En attente de validation'), ('approved', 'Validé'), ('rejected', 'Rejeté'), ('in_transit', 'En transit'), ('delivered', 'Livré'), ('exported', 'Exporté'), ('locked', 'Verrouillé (blockchain)')], default='draft', max_length=20)),
                ('unique_code', models.CharField(help_text='Code QR unique : TRC-YYYY-XXXX', max_length=50, unique=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, limit_choices_to={'is_store': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(choices=[('FARM_TO_COOP', 'Ferme → Coopérative'), ('COOP_TO_TRANSPORTER', 'Coopérative → Transporteur'), ('TRANSPORTER_TO_EXPORTER', 'Transporteur → Exportateur'), ('EXPORTER_TO_EU_IMPORTER', 'Exportateur → Importateur EU'), ('CUSTOM', 'Transfert personnalisé')], default='CUSTOM', max_length=30)),
                ('quantity', models.FloatField(help_text='Quantité transférée en kg')),
                ('price_per_kg', models.FloatField(blank=True, help_text='Prix au kg (FCFA)', null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Lieu du transfert', max_length=255, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='stock.batch')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(help_text='Quantité récoltée en kg')),
                ('harvest_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='stock.batch')),
                ('farmer', models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gps_coordinates', models.JSONField(help_text='Polygone GPS — liste de {lat, lng}, min 3 points (EUDR)')),
                ('area', models.FloatField(blank=True, help_text='Superficie en hectares (calculée automatiquement)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, limit_choices_to={'is_store': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.parcel'),
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='StockDestination',
        ),
        migrations.DeleteModel(
            name='StockOrigin',
        ),
    ]
