# Generated by Django 6.0.4 on 2026-05-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stockproducer_farm_and_more'),
        ('tracability', '0004_alter_batchcertification_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockProducer',
        ),
        migrations.DeleteModel(
            name='StockTransporter',
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['batch'], name='idx_transfers_batch'),
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['sender'], name='idx_transfers_sender'),
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['receiver'], name='idx_transfers_receiver'),
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['status'], name='idx_transfers_status'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['batch'], name='idx_harvests_batch'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_date'], name='idx_harvests_date'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['farmer'], name='idx_parcels_farmer'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='idx_parcels_status'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['farmer'], name='idx_batches_farmer'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['parcel'], name='idx_batches_parcel'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='idx_batches_status'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['unique_code'], name='idx_batches_code'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('parcel', 'season', 'crop_type')},
        ),
    ]
